name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        nvim-version: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        shell: bash
        run: |
          wget -q https://github.com/neovim/neovim/releases/download/${{ matrix.nvim-version }}/nvim-linux-x86_64.tar.gz -O /tmp/nvim-linux-x86_64.tar.gz
          sudo tar zxf /tmp/nvim-linux-x86_64.tar.gz -C /tmp/
      - name: Run Neovim
        run: |
          sudo mkdir -p ~/.config/nvim
          sudo cp -rf * ~/.config/nvim/
          sudo /tmp/nvim-linux-x86_64/bin/nvim --version
          sudo /tmp/nvim-linux-x86_64/bin/nvim --headless -c "checkhealth" -c "quit" -c "quit"
  release:
    name: release
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
