name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        nvim-version: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Neovim
        shell: bash
        run: |
          wget -q https://github.com/neovim/neovim/releases/download/${{ matrix.nvim-version }}/nvim-linux64.deb -O /tmp/nvim.deb
          sudo dpkg -i /tmp/nvim.deb
      - name: Run Neovim
        run: |
          sudo mkdir -p ~/.config/nvim
          sudo cp -rf * ~/.config/nvim/
          sudo nvim --version
          sudo nvim --headless -c "checkhealth" -c "quit" -c "quit"
